# deploy

name: deploy

on:
  workflow_dispatch:
    inputs:
      application-id:
        type: choice
        description: Application Id
        options: 
        - org.prototype.mobile
        - org.gacco.mobile.sandbox

env:
  application-id: ${{ github.event.inputs.application-id }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - run: echo ${{github.ref}}

    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '8'

#    - name: Restore keystore
#      run: echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > ./OpenEdXMobile/${{secrets.DEBUG_KEYSTORE_STORE_FILE}}

#    - name: Build App Bundle
#      env:
#        DEBUG_KEYSTORE_STORE_FILE: ${{secrets.DEBUG_KEYSTORE_STORE_FILE}}
#        DEBUG_KEYSTORE_STORE_PASSWORD: ${{secrets.DEBUG_KEYSTORE_STORE_PASSWORD}}
#        DEBUG_KEYSTORE_KEY_ALIAS: ${{secrets.DEBUG_KEYSTORE_KEY_ALIAS}}
#        DEBUG_KEYSTORE_KEY_PASSWORD: ${{secrets.DEBUG_KEYSTORE_KEY_PASSWORD}}
#      run: ./gradlew ${{ github.event.inputs.task }}

    - run: sed -i 's/org.edx.mobile/${{ env.application-id }}/g' constants.gradle

#    - run: echo "build-number=$(date +'%y%m%d%H%M')" >> $GITHUB_ENV
#      env:
#        TZ: 'Asia/Tokyo'

    - uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: OpenEdXMobile/build.gradle
        versionCode: ${{ github.run_number }}
    - run: cat OpenEdXMobile/build.gradle

    - run: ./gradlew bundleProdRelease

    - uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: OpenEdXMobile/build/outputs/bundle/prodRelease
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

#    - run: echo '${{ secrets.SERVICE_ACCOUNT_JSON_DEVELOP }}' > service_account.json

    - uses: devussy/upload-google-play@v1.0.6
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_DEVELOP }}
        packageName: ${{ env.application-id }}
        releaseFile: OpenEdXMobile/build/outputs/bundle/prodRelease/OpenEdXMobile.aab
        track: internal

#    - uses: r0adkll/upload-google-play@v1
#      with:
#        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_DEVELOP }}
#        packageName: ${{ env.application-id }}
#        releaseFiles: OpenEdXMobile/build/outputs/bundle/prodRelease/OpenEdXMobile.aab
#        track: internal
#        status: draft
